name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g github-readme-stats

      - name: Update GitHub stats
        run: |
          github-readme-stats --username=yourgithubusername --theme=dark
 
