name: Auto-update Blog Showcase

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Update Blog with Latest Project
        run: |
          python update_blog.py
 
